<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>InfiniteCharmsMod</AssemblyName>
    <RootNamespace>InfiniteCharmsMod</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Modding">
      <HintPath>libs/ModManager.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>